### ISSUE TITLE
PKCS12_parse: mac verify failure

### ISSUE THREAD

**Issue by wqyer** [jasl/wx_pay#49]
``` ruby
/Users/hastings/.rvm/gems/ruby-2.2.3@thalassa/gems/wx_pay-0.12.0/lib/wx_pay.rb:15:in `initialize': PKCS12_parse: mac verify failure (OpenSSL::PKCS12::PKCS12Error)
	from /Users/hastings/.rvm/gems/ruby-2.2.3@thalassa/gems/wx_pay-0.12.0/lib/wx_pay.rb:15:in `new'
	from /Users/hastings/.rvm/gems/ruby-2.2.3@thalassa/gems/wx_pay-0.12.0/lib/wx_pay.rb:15:in `set_apiclient_by_pkcs12'
	from /Users/hastings/workspace/thalassa/config/initializers/wx_pay.rb:1:in `<top (required)>'
	from /Users/hastings/.rvm/gems/ruby-2.2.3@thalassa/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /Users/hastings/.rvm/gems/ruby-2.2.3@thalassa/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/hastings/.rvm/gems/ruby-2.2.3@thalassa/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/hastings/.rvm/gems/ruby-2.2.3@thalassa/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
```

**Comment by wqyer** [comment]
``` ruby
WxPay.set_apiclient_by_pkcs12(File.read("apiclient_cert.p12"), ENV['wxpay_mch_id'])
```

**Comment by wqyer** [comment]
这个怎么搞，google说用`File.read("UserCert.p12", "rb")`或`File.binread('UserCert.p12')`，尝试后都不行
