### ISSUE TITLE
出现这个错误service.rb:330:in `invoke_remote'

### ISSUE THREAD

**Issue by guoyoujin** [jasl/wx_pay#64]
`调用WxPay::Service.invoke_unifiedorder(params)出现如下错误`
```
RestClient::Exceptions::OpenTimeout (Timed out connecting to server):
  lib/wx_pay/lib/wx_pay/service.rb:330:in `invoke_remote'
  lib/wx_pay/lib/wx_pay/service.rb:39:in `invoke_unifiedorder'

```

**Comment by jasl** [comment]
这异常说的很清楚，超时了啊。。。你要是设置 `rest_client` 的超时时间的话，就适当调高点，不然就检查你服务器到微信服务器的连通性了

**Comment by guoyoujin** [comment]
确实是超时引起的，用的你的文档里面配置
```
WxPay.extra_rest_client_options = {timeout: 2, open_timeout: 3}
```
感觉时间设置太小了，很容易引起这个问题
我就在后面加了个零

```
WxPay.extra_rest_client_options = {timeout: 20, open_timeout: 30}
```
